version: "3.9"

services:
  postgres:
    container_name: ndk-go-server-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    env_file:
      - ./../config/app.env
    volumes:
#      - ./../db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local